export const ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",

    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",

    INVITATION_NOT_FOUND: "INVITATION_NOT_FOUND",
    INVITATION_EXPIRED: "INVITATION_EXPIRED",
    INVITATION_ALREADY_USED: "INVITATION_ALREADY_USED",

    DOCTOR_NOT_FOUND: "DOCTOR_NOT_FOUND",
    PATIENT_NOT_FOUND: "PATIENT_NOT_FOUND",

    APPOINTMENT_NOT_FOUND: "APPOINTMENT_NOT_FOUND",
    APPOINTMENT_CONFLICT: "APPOINTMENT_CONFLICT",

    AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",

    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",

    INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;